import 'package:flutter/material.dart';
import 'package:recurrly/core/constants/icons.dart';
import 'package:recurrly/features/home/data/models/subscription_detail_model.dart';
import 'package:recurrly/features/home/presentation/widgets/home_subscription_tile.dart';

final List<SubscriptionDetailModel> subscriptions = [
  SubscriptionDetailModel(
    icon: RIcons.netflix,
    amount: 15.99,
    daysLeft: "12",
    subscriptionName: 'Netflix',
  ),
  SubscriptionDetailModel(
    icon: RIcons.spotify,
    amount: 9.99,
    daysLeft: "25",
    subscriptionName: 'Spotify',
  ),
  SubscriptionDetailModel(
    icon: RIcons.adobe,
    amount: 29.99,
    daysLeft: "5",
    subscriptionName: 'Adobe Creative Cloud',
  ),
  SubscriptionDetailModel(
    icon: RIcons.openai,
    amount: 20.00,
    daysLeft: "18",
    subscriptionName: 'OpenAI',
  ),
  SubscriptionDetailModel(
    icon: RIcons.notion,
    amount: 8.00,
    daysLeft: "30",
    subscriptionName: 'Notion',
  ),
  SubscriptionDetailModel(
    icon: RIcons.github,
    amount: 4.00,
    daysLeft: "14",
    subscriptionName: 'GitHub',
  ),
  SubscriptionDetailModel(
    icon: RIcons.canva,
    amount: 12.99,
    daysLeft: "9",
    subscriptionName: 'Canva',
  ),
  SubscriptionDetailModel(
    icon: RIcons.figma,
    amount: 15.00,
    daysLeft: "21",
    subscriptionName: 'Figma',
  ),
  SubscriptionDetailModel(
    icon: RIcons.dropbox,
    amount: 11.99,
    daysLeft: "3",
    subscriptionName: 'Dropbox',
  ),
  SubscriptionDetailModel(
    icon: RIcons.medium,
    amount: 5.00,
    daysLeft: "27",
    subscriptionName: 'Medium',
  ),
  SubscriptionDetailModel(
    icon: RIcons.claude,
    amount: 18.00,
    daysLeft: "16",
    subscriptionName: 'Claude',
  ),
];

final List<HomeSubscriptionTile> homeSubscriptions = [
  HomeSubscriptionTile(
    icon: RIcons.netflix,
    titleBackgroundColor: Color(0xFFFFE5E5),
    iconBackgroundColor: Color(0xFFFF3B30),
    subscriptionName: 'Netflix',
    date: DateTime(2026, 5, 12, 10, 30),
    amount: 15.99,
    duration: 'Monthly',
  ),
  HomeSubscriptionTile(
    icon: RIcons.spotify,
    titleBackgroundColor: Color(0xFFE6F9F0),
    iconBackgroundColor: Color(0xFF1DB954),
    subscriptionName: 'Spotify',
    date: DateTime(2026, 5, 20, 9, 0),
    amount: 9.99,
    duration: 'Monthly',
  ),
  HomeSubscriptionTile(
    icon: RIcons.adobe,
    titleBackgroundColor: Color(0xFFFFF4E5),
    iconBackgroundColor: Color(0xFFFF2D20),
    subscriptionName: 'Adobe CC',
    date: DateTime(2026, 5, 5, 14, 15),
    amount: 29.99,
    duration: 'Monthly',
  ),
  HomeSubscriptionTile(
    icon: RIcons.openai,
    titleBackgroundColor: Color(0xFFEAF2FF),
    iconBackgroundColor: Color(0xFF4A90E2),
    subscriptionName: 'OpenAI',
    date: DateTime(2026, 5, 18, 11, 45),
    amount: 20.00,
    duration: 'Monthly',
  ),
  // HomeSubscriptionTile(
  //   icon: RIcons.notion,
  //   titleBackgroundColor: Color(0xFFF2F2F2),
  //   iconBackgroundColor: Colors.white,
  //   subscriptionName: 'Notion',
  //   date: DateTime(2026, 5, 25, 8, 30),
  //   amount: 8.00,
  //   duration: 'Monthly',
  // ),
  // HomeSubscriptionTile(
  //   icon: RIcons.github,
  //   titleBackgroundColor: Color(0xFFEDEDED),
  //   iconBackgroundColor: Colors.white,
  //   subscriptionName: 'GitHub',
  //   date: DateTime(2026, 5, 10, 16, 0),
  //   amount: 4.00,
  //   duration: 'Monthly',
  // ),
  HomeSubscriptionTile(
    icon: RIcons.canva,
    titleBackgroundColor: Color(0xFFE6F7FF),
    iconBackgroundColor: Color(0xFF00C4CC),
    subscriptionName: 'Canva',
    date: DateTime(2026, 5, 14, 13, 20),
    amount: 12.99,
    duration: 'Monthly',
  ),
  HomeSubscriptionTile(
    icon: RIcons.figma,
    titleBackgroundColor: Color(0xFFFFEFE6),
    iconBackgroundColor: Color(0xFFF24E1E),
    subscriptionName: 'Figma',
    date: DateTime(2026, 5, 22, 10, 10),
    amount: 15.00,
    duration: 'Monthly',
  ),
  HomeSubscriptionTile(
    icon: RIcons.dropbox,
    titleBackgroundColor: Color(0xFFE6F0FF),
    iconBackgroundColor: Color(0xFF0061FF),
    subscriptionName: 'Dropbox',
    date: DateTime(2026, 5, 8, 17, 45),
    amount: 11.99,
    duration: 'Monthly',
  ),
  // HomeSubscriptionTile(
  //   icon: RIcons.medium,
  //   titleBackgroundColor: Color(0xFFEFEFEF),
  //   iconBackgroundColor: Color(0xFF12100E),
  //   subscriptionName: 'Medium',
  //   date: DateTime(2026, 5, 28, 7, 50),
  //   amount: 5.00,
  //   duration: 'Monthly',
  // ),
  HomeSubscriptionTile(
    icon: RIcons.claude,
    titleBackgroundColor: Color(0xFFEDE7FF),
    iconBackgroundColor: Color(0xFF6C5CE7),
    subscriptionName: 'Claude',
    date: DateTime(2026, 5, 16, 12, 0),
    amount: 18.00,
    duration: 'Monthly',
  ),
];
